services:
  database:
    image: pgvector/pgvector:pg18-trixie
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
  redis:
    image: redis
    restart: always
    ports:
      - "6380:6379"
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
